---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2
  - name: debian-8.1
    run_list: apt::default
  - name: fedora-21
  - name: fedora-22

suites:
  - name: default
    run_list:
      - recipe[webserver::default]
    attributes:
  - name: custom
    run_list:
      - recipe[webserver::default]
    attributes:
